name: humano
favicon: null
layout_spectrum: 0.36036
typography_spectrum: 0.12804
title: Humano Bodywork
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1819'
    - '#ffffff'
    - '#464344'
    - '#b7b5b6'
    - '#949293'
  brandStrength: 0.8125
  lightness: 0.9376741179730743
  saturation: 0.25392946717329323
  rhythmicContrast: 0.16918652667663991
purpose: []
